/**
 * chapter-data.js - v23.1 Chapter system configuration
 * Defines chapter structure, BOSS monsters, chapter-exclusive monsters,
 * exclusive items/weapons, and rewards.
 * v23.1: Added 33 new chapter-exclusive monsters, 6 new items, 3 new weapons,
 *        updated unlock conditions to use consecutivePerfects.
 */

// ===== Chapter BOSS Monsters =====
var chapterBossMonsters = {
    xiaojiujiu: [
        {
            id: 'xjj_ch1_boss',
            name: '口诀守门人',
            nameEn: 'Formula Gatekeeper',
            emoji: '🗿',
            hp: 6,
            type: 'rock',
            attack: '📖',
            attackName: '口诀压制',
            behaviors: ['defend'],
            personality: 'defensive',
            quips: ['口诀不熟，休想通过！', '我守了千年，无人能过！', '背不出来就回去！'],
            defendQuips: ['石墙坚不可摧！', '千年守护！', '挡！'],
            trait: '守护数学王国大门千年的石像，只放行掌握口诀的人',
            traitEn: 'An ancient stone guardian that only lets those who master multiplication pass',
            story: '传说口诀守门人原本是一位数学老师，因太执着于九九乘法表而化为石像，守护着数学王国的大门。只有真正掌握基础口诀的人，才能唤醒他心中残存的温柔。',
            storyEn: 'Legend says the Gatekeeper was once a math teacher, turned to stone by his obsession with multiplication tables.',
            isBoss: true,
            isChapterBoss: true,
            chapter: 'xjj_ch1'
        },
        {
            id: 'xjj_ch2_boss',
            name: '速算将军',
            nameEn: 'Speed General',
            emoji: '⚔️',
            hp: 8,
            type: 'fighting',
            attack: '💢',
            attackName: '疾风连斩',
            behaviors: ['enrage', 'counter'],
            personality: 'violent',
            quips: ['太慢了！', '速度就是力量！', '看我的疾风斩！', '算不快就别来！'],
            enrageQuips: ['还不够快！！', '让你见识真正的速度！', '怒！'],
            counterQuips: ['反击！', '太大意了！', '接招！'],
            trait: '以速度著称的武将，答错会遭到反击',
            traitEn: 'A general known for speed, who counterattacks when you answer wrong',
            story: '速算将军曾是王国最快的计算师，因追求极限速度而走火入魔。他挥舞双剑，只尊重能跟上他节奏的对手。',
            storyEn: 'The Speed General was once the kingdom\'s fastest calculator, driven mad by his pursuit of speed.',
            isBoss: true,
            isChapterBoss: true,
            chapter: 'xjj_ch2'
        },
        {
            id: 'xjj_ch3_boss',
            name: '九九魔帝',
            nameEn: 'Emperor of Nines',
            emoji: '👑',
            hp: 10,
            type: 'dragon',
            attack: '🌟',
            attackName: '九九归一',
            behaviors: ['defend', 'summon', 'enrage', 'counter'],
            personality: 'sinister',
            quips: ['九九归一，万法归宗！', '你敢挑战本帝？', '跪下！', '数学的极致在此！'],
            defendQuips: ['帝王之盾！', '不可能打穿！', '挡！'],
            summonQuips: ['来人！护驾！', '小的们，上！', '援军无穷无尽！'],
            enrageQuips: ['你激怒了本帝！', '死！', '天地变色！'],
            counterQuips: ['反击！感受帝王之怒！', '不自量力！', '回敬你！'],
            trait: '统治九九王国的最终BOSS，拥有两种形态',
            traitEn: 'The ultimate boss ruling the Kingdom of Nines, with two powerful forms',
            story: '九九魔帝是所有乘法口诀的化身，只有真正掌握九九乘法的勇者才能将其打败。传说他的两种形态分别代表乘法和除法的极致力量。',
            storyEn: 'The Emperor of Nines is the embodiment of all multiplication tables.',
            isBoss: true,
            isChapterBoss: true,
            chapter: 'xjj_ch3',
            // Phase 2 configuration
            phase2: true,
            phase2Emoji: '🐲',
            phase2Name: '真·九九魔帝',
            phase2HP: 6,
            phase2Attack: '💥',
            phase2AttackName: '九九归一·帝王版',
            phase2Behaviors: ['enrage', 'counter', 'summon', 'curse'],
            phase2Quips: ['这才是本帝的真面目！', '变身！感受绝望吧！', '没有人能打败真正的魔帝！']
        }
    ]
};

// ===== v23.1: Chapter-Exclusive Monsters (33 new) =====

// --- Chapter 1: 口诀精灵 (8 monsters) ---
var chapterMonsters_ch1 = [
    {
        id: 'xjj_ch1_ersan',
        name: '二三虫',
        nameEn: 'Two-Three Caterpillar',
        emoji: '🐛',
        hp: 3,
        type: 'bug',
        attack: '🍃',
        attackName: '口诀念叨',
        behaviors: [],
        personality: 'timid',
        quips: ['二三得六…二三得六…', '别打我呀…', '我只是在背口诀…'],
        trait: '总念叨"二三得六"的毛毛虫，胆子很小',
        traitEn: 'A shy caterpillar that constantly mumbles "2×3=6"',
        story: '二三虫原是一片树叶上的小毛虫，因为日夜听着风吹过树叶发出"二三得六"的声音而觉醒了数学意识。它现在只会背这一句口诀，但背得非常认真。',
        storyEn: 'A small caterpillar that gained math awareness from listening to leaves rustling "2×3=6".',
        isChapterMonster: true,
        chapter: 'xjj_ch1'
    },
    {
        id: 'xjj_ch1_siwu',
        name: '四五蛙',
        nameEn: 'Four-Five Frog',
        emoji: '🐸',
        hp: 3,
        type: 'water',
        attack: '💧',
        attackName: '呱呱口诀',
        behaviors: [],
        personality: 'timid',
        quips: ['呱！四五二十！', '呱呱…答错了哦…', '池塘里的口诀大王！'],
        trait: '呱呱叫着"四五二十"的小青蛙',
        traitEn: 'A frog that croaks "4×5=20" from its pond',
        story: '四五蛙住在数学王国的口诀池塘里，每天跳20下练习乘法。其他青蛙都觉得它很奇怪，但它坚信"四五二十"是世界上最美的旋律。',
        storyEn: 'A frog living in the Formula Pond that practices multiplication by jumping exactly 20 times daily.',
        isChapterMonster: true,
        chapter: 'xjj_ch1'
    },
    {
        id: 'xjj_ch1_liuqi',
        name: '六七萤',
        nameEn: 'Six-Seven Firefly',
        emoji: '🪲',
        hp: 3,
        type: 'bug',
        attack: '✨',
        attackName: '萤光闪烁',
        behaviors: ['dodge'],
        personality: 'cunning',
        quips: ['六七四十二～闪！', '你看得到我吗？', '忽明忽暗，算不准吧！'],
        dodgeQuips: ['闪！', '抓不到～', '萤光遁走！'],
        trait: '忽明忽暗的萤火虫，喜欢"六七四十二"',
        traitEn: 'A flickering firefly that loves "6×7=42"',
        story: '六七萤是夜晚口诀森林中最亮的虫子。它闪烁的频率正好是每分钟42次，对应"六七四十二"。想要打中它，得先算对口诀才行！',
        storyEn: 'The brightest bug in the Formula Forest, flickering exactly 42 times per minute.',
        isChapterMonster: true,
        chapter: 'xjj_ch1'
    },
    {
        id: 'xjj_ch1_baba',
        name: '八八猫',
        nameEn: 'Eight-Eight Cat',
        emoji: '🐱',
        hp: 4,
        type: 'normal',
        attack: '🐾',
        attackName: '猫爪乱拍',
        behaviors: [],
        personality: 'timid',
        quips: ['喵～八八六十四！', '别碰我的毛球！', '六十四根猫须，一根都不能少！'],
        trait: '爱说"八八六十四"的橘猫，有64根骄傲的猫须',
        traitEn: 'An orange tabby cat proud of its 64 whiskers, loves "8×8=64"',
        story: '八八猫是数学王国最胖的橘猫，它总说自己有六十四根猫须所以最尊贵。事实上它只有32根，但它坚持"八八六十四"才是正确答案。',
        storyEn: 'The fattest orange tabby in the Math Kingdom, who insists it has 64 whiskers because "8×8=64".',
        isChapterMonster: true,
        chapter: 'xjj_ch1'
    },
    {
        id: 'xjj_ch1_jiujiu',
        name: '九九鸟',
        nameEn: 'Nine-Nine Bird',
        emoji: '🐦',
        hp: 4,
        type: 'flying',
        attack: '🎵',
        attackName: '口诀歌声',
        behaviors: ['dodge'],
        personality: 'cunning',
        quips: ['九九八十一～啾啾！', '飞得高算得快！', '唱着口诀飞上天！'],
        dodgeQuips: ['飞走啦！', '太慢了～', '啾！'],
        trait: '唱着"九九八十一"的小鸟，飞行灵活',
        traitEn: 'A nimble bird that sings "9×9=81" while flying',
        story: '九九鸟据说是九九乘法表化成的精灵。它在天空中画出的飞行轨迹，如果连起来就是完整的九九乘法表。没有人能轻易抓住会飞的口诀！',
        storyEn: 'A spirit born from the multiplication table itself, its flight path traces out the entire times table.',
        isChapterMonster: true,
        chapter: 'xjj_ch1'
    },
    {
        id: 'xjj_ch1_suanpan',
        name: '算盘蜘蛛',
        nameEn: 'Abacus Spider',
        emoji: '🕷️',
        hp: 4,
        type: 'bug',
        attack: '🕸️',
        attackName: '算盘丝网',
        behaviors: ['taunt'],
        personality: 'cunning',
        quips: ['我的网就是算盘！', '被我缠住就算不出来了！', '丝丝入扣，一个都别想跑！'],
        tauntQuips: ['怕了吧？', '这题你肯定不会！', '哈哈！'],
        trait: '用蛛网织算盘的蜘蛛，会嘲讽干扰你',
        traitEn: 'A spider that weaves abacus patterns with its web and taunts its opponents',
        story: '算盘蜘蛛的祖先曾是一把古老的算盘，被遗弃在角落里生了蜘蛛。久而久之，蜘蛛学会了用蛛丝编织算盘，还爱嘲笑算错的人。',
        storyEn: 'Descendant of a spider that lived on an abandoned abacus, it learned to weave calculation webs.',
        isChapterMonster: true,
        chapter: 'xjj_ch1'
    },
    {
        id: 'xjj_ch1_koujue',
        name: '口诀小精灵',
        nameEn: 'Formula Sprite',
        emoji: '🧚',
        hp: 3,
        type: 'fairy',
        attack: '💫',
        attackName: '口诀之光',
        behaviors: [],
        personality: 'timid',
        quips: ['口诀～口诀～', '数字在发光！', '记住口诀就不怕我啦！'],
        trait: '漂浮的口诀化身，温柔但需要被答对才会消散',
        traitEn: 'A floating embodiment of multiplication formulas, gentle but persistent',
        story: '口诀小精灵是乘法口诀凝聚而成的光之生物。它不会攻击人，只是默默飘浮着，等待有人正确地背出它代表的口诀。答对了，它就会化为光芒消散。',
        storyEn: 'A luminous creature formed from condensed multiplication formulas, waiting for someone to recite correctly.',
        isChapterMonster: true,
        chapter: 'xjj_ch1'
    },
    {
        id: 'xjj_ch1_shuxue',
        name: '数字泥人',
        nameEn: 'Number Golem',
        emoji: '🧱',
        hp: 4,
        type: 'rock',
        attack: '🧱',
        attackName: '数字砖块',
        behaviors: ['defend'],
        personality: 'defensive',
        quips: ['我是数字堆成的！', '打不动的！', '1234…组合起来力量无穷！'],
        defendQuips: ['硬如磐石！', '数字之墙！', '挡住！'],
        trait: '由数字堆叠而成的泥人，防御力高',
        traitEn: 'A golem made of stacked numbers with high defense',
        story: '数字泥人是由做错的算术题堆积而成的。每一块砖上都写着一个被答错的数字，它的使命是阻止不认真学习的人通过。只有答对题目才能削弱它的砖墙。',
        storyEn: 'A golem built from incorrectly answered math problems, blocking those who don\'t study seriously.',
        isChapterMonster: true,
        chapter: 'xjj_ch1'
    }
];

// --- Chapter 2: 速算武士 (12 monsters) ---
var chapterMonsters_ch2 = [
    {
        id: 'xjj_ch2_shuriken',
        name: '手里剑鼠',
        nameEn: 'Shuriken Mouse',
        emoji: '🐭',
        hp: 4,
        type: 'fighting',
        attack: '🌀',
        attackName: '数字手里剑',
        behaviors: ['dodge'],
        personality: 'cunning',
        quips: ['接招！数字手里剑！', '快如闪电！', '忍者鼠参上！'],
        dodgeQuips: ['影遁！', '太慢了！', '闪开！'],
        trait: '投掷数字手里剑的忍者鼠，速度极快',
        traitEn: 'A ninja mouse that throws number-engraved shuriken at lightning speed',
        story: '手里剑鼠是速算道场的优秀弟子，它将乘法口诀刻在手里剑上，每一击都带着数学的力量。据说它投出手里剑的速度和算题一样快。',
        storyEn: 'A top student at the Speed Math Dojo who engraves multiplication formulas on shuriken.',
        isChapterMonster: true,
        chapter: 'xjj_ch2'
    },
    {
        id: 'xjj_ch2_hayabusa',
        name: '隼风蜂',
        nameEn: 'Falcon Wasp',
        emoji: '🐝',
        hp: 4,
        type: 'flying',
        attack: '💨',
        attackName: '疾风蜇刺',
        behaviors: ['dodge'],
        personality: 'cunning',
        quips: ['嗡！速度就是一切！', '比风还快！', '你跟得上我吗？'],
        dodgeQuips: ['嗡嗡～闪！', '抓不到！', '太慢了！'],
        trait: '疾风般的数学黄蜂，飞行速度极快',
        traitEn: 'A mathematical wasp that flies faster than the wind',
        story: '隼风蜂得名于它堪比猎隼的飞行速度。在速算战场上，它是最令人头疼的对手——不仅飞得快，还会在你犹豫的瞬间发动攻击。',
        storyEn: 'Named after the peregrine falcon for its incredible speed, it attacks the moment you hesitate.',
        isChapterMonster: true,
        chapter: 'xjj_ch2'
    },
    {
        id: 'xjj_ch2_kenshi',
        name: '剑齿虎',
        nameEn: 'Saber Tiger',
        emoji: '🐯',
        hp: 5,
        type: 'fighting',
        attack: '⚔️',
        attackName: '乘法剑击',
        behaviors: ['enrage'],
        personality: 'violent',
        quips: ['乘法之剑！斩！', '看我的利齿！', '谁敢挡路！'],
        enrageQuips: ['怒吼！！', '力量暴涨！', '不可阻挡！'],
        trait: '挥舞乘法之剑的剑齿虎，暴怒时攻击翻倍',
        traitEn: 'A saber-toothed tiger wielding the Sword of Multiplication, doubles attack when enraged',
        story: '剑齿虎是速算将军的先锋战士，它的两颗剑齿象征着乘法中的两个因数。当它暴怒时，两颗剑齿发出金光，攻击力成倍增长。',
        storyEn: 'The Speed General\'s vanguard, its two saber teeth represent the two factors in multiplication.',
        isChapterMonster: true,
        chapter: 'xjj_ch2'
    },
    {
        id: 'xjj_ch2_ninja',
        name: '忍算者',
        nameEn: 'Ninja Calculator',
        emoji: '🥷',
        hp: 5,
        type: 'dark',
        attack: '🌑',
        attackName: '暗算术',
        behaviors: ['dodge', 'taunt'],
        personality: 'cunning',
        quips: ['隐身！看不见我吧？', '暗算才是最高境界！', '从影中计算！'],
        dodgeQuips: ['影遁术！', '消失！', '无影无踪！'],
        tauntQuips: ['这题你一定算错！', '放弃吧！', '心算比你快十倍！'],
        trait: '隐身的速算忍者，会闪避和嘲讽',
        traitEn: 'An invisible speed-calculation ninja who dodges and taunts',
        story: '忍算者修习的是"暗算流"忍术——在敌人看不见的地方完成所有计算。它的嘲讽不是为了恶意，而是为了测试对手的心理素质。',
        storyEn: 'A ninja who practices the art of "shadow calculation", testing opponents\' mental fortitude.',
        isChapterMonster: true,
        chapter: 'xjj_ch2'
    },
    {
        id: 'xjj_ch2_senshi',
        name: '盾甲龟',
        nameEn: 'Shield Tortoise',
        emoji: '🐢',
        hp: 6,
        type: 'rock',
        attack: '🛡️',
        attackName: '口诀护盾',
        behaviors: ['defend'],
        personality: 'defensive',
        quips: ['我的壳上刻满了口诀！', '慢慢来，防御第一！', '打不破我的壳！'],
        defendQuips: ['龟壳防御！', '坚不可摧！', '挡住了！'],
        trait: '背壳刻满口诀的乌龟，防御极高',
        traitEn: 'A tortoise with multiplication tables carved on its shell, extremely high defense',
        story: '盾甲龟的龟壳上刻着完整的九九乘法表，是速算战场上最坚固的防线。据说只有全对的答案才能穿透它的口诀防壳。',
        storyEn: 'Its shell bears the complete multiplication table, forming the battlefield\'s strongest defense.',
        isChapterMonster: true,
        chapter: 'xjj_ch2'
    },
    {
        id: 'xjj_ch2_raijin',
        name: '雷算兽',
        nameEn: 'Thunder Calculator',
        emoji: '⚡',
        hp: 5,
        type: 'electric',
        attack: '⚡',
        attackName: '闪电速算',
        behaviors: ['enrage'],
        personality: 'violent',
        quips: ['闪电般的速度！', '电光火石之间！', '雷鸣！'],
        enrageQuips: ['雷霆万钧！', '电力全开！', '轰！'],
        trait: '以闪电速度出题的雷兽，暴怒时电光四射',
        traitEn: 'A thunder beast that poses questions at lightning speed',
        story: '雷算兽体内蕴含着数学的电能。它出题的速度如同闪电——在你还没反应过来的时候，题目就已经出完了。跟不上它的节奏就会被电击！',
        storyEn: 'A beast charged with mathematical electricity, posing questions faster than lightning.',
        isChapterMonster: true,
        chapter: 'xjj_ch2'
    },
    {
        id: 'xjj_ch2_kaze',
        name: '旋风狐',
        nameEn: 'Whirlwind Fox',
        emoji: '🦊',
        hp: 5,
        type: 'flying',
        attack: '🌪️',
        attackName: '数字旋风',
        behaviors: ['dodge'],
        personality: 'cunning',
        quips: ['旋风中的数字看得清吗？', '狐狸比你聪明！', '呼～旋转！'],
        dodgeQuips: ['风遁！', '旋转闪避！', '追不上！'],
        trait: '卷着数字旋风的狐狸，灵活善变',
        traitEn: 'A fox that creates whirlwinds of swirling numbers',
        story: '旋风狐能用尾巴卷起带有数字的旋风，让题目的数字在风中旋转打乱。只有眼疾手快、心算精准的人才能在旋风中看清正确答案。',
        storyEn: 'A fox whose tail creates whirlwinds that scramble numbers, only sharp minds can see through.',
        isChapterMonster: true,
        chapter: 'xjj_ch2'
    },
    {
        id: 'xjj_ch2_tetsu',
        name: '铁壁蟹',
        nameEn: 'Iron Crab',
        emoji: '🦀',
        hp: 6,
        type: 'steel',
        attack: '🦾',
        attackName: '铁钳夹击',
        behaviors: ['defend'],
        personality: 'defensive',
        quips: ['铁壁！无人能破！', '我的铁甲最硬！', '夹住你！'],
        defendQuips: ['钢铁防御！', '铁壁合拢！', '挡！'],
        trait: '铁甲防御的算术螃蟹，双钳坚如钢铁',
        traitEn: 'An iron-armored arithmetic crab with steel-hard pincers',
        story: '铁壁蟹的甲壳由纯粹的数学逻辑凝结而成，比任何金属都坚硬。它的两只大钳子分别代表加法和减法——组合起来就是乘法的基础！',
        storyEn: 'Its shell is crystallized mathematical logic, harder than any metal.',
        isChapterMonster: true,
        chapter: 'xjj_ch2'
    },
    {
        id: 'xjj_ch2_honoo',
        name: '焰算猿',
        nameEn: 'Flame Calculator Ape',
        emoji: '🐵',
        hp: 5,
        type: 'fire',
        attack: '🔥',
        attackName: '烈火速算',
        behaviors: ['enrage'],
        personality: 'violent',
        quips: ['火焰加速！', '算得我都着火了！', '燃烧吧！数学之魂！'],
        enrageQuips: ['燃烧殆尽！', '怒火冲天！', '烈焰暴走！'],
        trait: '愤怒时火焰加速的猴子，越打越狂暴',
        traitEn: 'An ape that accelerates with flames when angry',
        story: '焰算猿是速算道场的狂战士，它的愤怒与火焰成正比——算错的题越多，它的火焰就越旺。据说它的终极形态是全身化为火焰的计算之神。',
        storyEn: 'A berserker from the Speed Math Dojo whose flames grow with each wrong answer.',
        isChapterMonster: true,
        chapter: 'xjj_ch2'
    },
    {
        id: 'xjj_ch2_yari',
        name: '枪术蜥蜴',
        nameEn: 'Spear Lizard',
        emoji: '🦎',
        hp: 5,
        type: 'fighting',
        attack: '🔱',
        attackName: '反击枪刺',
        behaviors: ['counter'],
        personality: 'violent',
        quips: ['看我的反击！', '枪术精通！', '敢答错就刺你！'],
        counterQuips: ['反击！', '破绽！', '一击必杀！'],
        trait: '精通反击的蜥蜴武士，答错必被刺',
        traitEn: 'A lizard warrior master of counterattacks',
        story: '枪术蜥蜴是速算战场上最精通反击的武士。它手中的长枪刻着"答错即罚"四个字，任何计算失误都会遭到它精准的反击。',
        storyEn: 'The battlefield\'s counterattack master, its spear is inscribed "wrong answers will be punished".',
        isChapterMonster: true,
        chapter: 'xjj_ch2'
    },
    {
        id: 'xjj_ch2_kage',
        name: '影分身蛇',
        nameEn: 'Shadow Clone Snake',
        emoji: '🐍',
        hp: 4,
        type: 'dark',
        attack: '🌑',
        attackName: '影分身攻击',
        behaviors: ['dodge', 'taunt'],
        personality: 'cunning',
        quips: ['哪个才是真的我？', '嘶～分身术！', '影子里藏着答案！'],
        dodgeQuips: ['那是分身！', '嘶嘶～消失！', '打中的是影子！'],
        tauntQuips: ['你分得清真假吗？', '迷惑了吧！', '嘶嘶嘶～'],
        trait: '制造影分身的速算蛇，让人真假难辨',
        traitEn: 'A snake that creates shadow clones, making it hard to tell real from fake',
        story: '影分身蛇掌握着"影分身之术"，能在战场上制造出多个分身。每个分身都会给出不同的答案，只有击中真身才能造成伤害。',
        storyEn: 'Master of the Shadow Clone technique, each clone gives a different answer.',
        isChapterMonster: true,
        chapter: 'xjj_ch2'
    },
    {
        id: 'xjj_ch2_arashi',
        name: '暴风鹰',
        nameEn: 'Storm Eagle',
        emoji: '🦅',
        hp: 6,
        type: 'flying',
        attack: '🌪️',
        attackName: '暴风突击',
        behaviors: ['enrage', 'dodge'],
        personality: 'violent',
        quips: ['暴风来临！', '在风暴中计算！', '翱翔！'],
        enrageQuips: ['暴风怒号！', '风暴升级！', '无法阻挡的风暴！'],
        dodgeQuips: ['乘风闪避！', '暴风中的幻影！', '飞！'],
        trait: '在暴风中精确计算的猛禽，暴怒时风暴加剧',
        traitEn: 'A raptor that calculates precisely within storms, storms intensify when enraged',
        story: '暴风鹰是速算战场的空中霸主。它能在最猛烈的暴风中保持精准计算，这也是速算将军最信赖的空中战力。挑战它需要同时具备速度和准确。',
        storyEn: 'The aerial lord of the Speed Battlefield, maintaining precise calculations even in fierce storms.',
        isChapterMonster: true,
        chapter: 'xjj_ch2'
    }
];

// --- Chapter 3: 魔帝军团 (13 monsters) ---
var chapterMonsters_ch3 = [
    {
        id: 'xjj_ch3_golem',
        name: '算式魔像',
        nameEn: 'Formula Golem',
        emoji: '🤖',
        hp: 6,
        type: 'steel',
        attack: '⚙️',
        attackName: '错误算式冲击',
        behaviors: ['defend', 'enrage'],
        personality: 'defensive',
        quips: ['错误…组合…力量…', '我是错误的集合体！', '打碎我需要正确答案！'],
        defendQuips: ['钢铁之墙！', '错误堆叠！', '不可穿透！'],
        enrageQuips: ['错误暴走！', '算式崩坏！', '疯狂运算！'],
        trait: '由错误算式拼成的巨型魔像，防御与狂暴兼备',
        traitEn: 'A massive golem assembled from incorrect equations',
        story: '算式魔像是由无数学生做错的算术题残片拼凑而成的怪物。它的存在本身就是"错误"的化身，只有正确的答案才能瓦解它的身躯。',
        storyEn: 'A monster assembled from countless students\' incorrect math answers.',
        isChapterMonster: true,
        chapter: 'xjj_ch3'
    },
    {
        id: 'xjj_ch3_dragon_jr',
        name: '幼龙卫兵',
        nameEn: 'Dragon Guard Jr.',
        emoji: '🐉',
        hp: 6,
        type: 'dragon',
        attack: '🔥',
        attackName: '龙息吐焰',
        behaviors: ['enrage'],
        personality: 'violent',
        quips: ['为魔帝而战！', '龙息！', '小小勇者，不自量力！'],
        enrageQuips: ['龙之怒火！', '燃尽一切！', '吼！！'],
        trait: '魔帝座下的幼龙侍卫，忠诚而暴烈',
        traitEn: 'A young dragon guard serving under the Emperor, loyal and fierce',
        story: '幼龙卫兵是九九魔帝亲自孵化的龙族侍卫。虽然还年幼，但它的龙息已经能融化普通的计算错误。只有全对才能抵挡住它的火焰。',
        storyEn: 'Hatched by the Emperor of Nines himself, its dragon breath melts ordinary calculation errors.',
        isChapterMonster: true,
        chapter: 'xjj_ch3'
    },
    {
        id: 'xjj_ch3_lich',
        name: '算灵巫师',
        nameEn: 'Calculation Lich',
        emoji: '🧙',
        hp: 7,
        type: 'psychic',
        attack: '🔮',
        attackName: '混淆诅咒',
        behaviors: ['curse', 'defend'],
        personality: 'sinister',
        quips: ['让你的答案扭曲吧…', '诅咒！混淆！', '你已经分不清对错了…'],
        curseQuips: ['诅咒降临！', '混沌之力！', '迷惑！'],
        defendQuips: ['魔法护盾！', '巫师结界！', '挡！'],
        trait: '用诅咒混淆答案的巫师，擅长心理战',
        traitEn: 'A lich that curses to confuse answers, master of psychological warfare',
        story: '算灵巫师原本是数学王国的大法师，被魔帝的力量腐化后堕落为亡灵巫师。它的诅咒能让人把正确答案看成错误的，是最恐怖的心理战高手。',
        storyEn: 'Once the kingdom\'s great wizard, corrupted by the Emperor\'s power into an undead lich.',
        isChapterMonster: true,
        chapter: 'xjj_ch3'
    },
    {
        id: 'xjj_ch3_shadow',
        name: '暗影刺客',
        nameEn: 'Shadow Assassin',
        emoji: '👤',
        hp: 5,
        type: 'dark',
        attack: '🗡️',
        attackName: '暗杀突袭',
        behaviors: ['dodge', 'counter'],
        personality: 'cunning',
        quips: ['从暗影中来…', '致命一击！', '你看不见我…'],
        dodgeQuips: ['消散在暗影中！', '只是残影…', '无影！'],
        counterQuips: ['暗杀反击！', '致命破绽！', '一击致命！'],
        trait: '从暗处反击的刺客，闪避与反击兼备',
        traitEn: 'An assassin that counterattacks from the shadows',
        story: '暗影刺客是魔帝军团中最神秘的存在。没人知道它的真实面目，只知道在你答错的瞬间，它的匕首就会从暗影中刺来。保持警惕，一题都不能错！',
        storyEn: 'The most mysterious member of the Emperor\'s legion, striking from shadows at every wrong answer.',
        isChapterMonster: true,
        chapter: 'xjj_ch3'
    },
    {
        id: 'xjj_ch3_titan',
        name: '数字巨人',
        nameEn: 'Number Titan',
        emoji: '👹',
        hp: 8,
        type: 'rock',
        attack: '💪',
        attackName: '巨力砸击',
        behaviors: ['defend', 'enrage'],
        personality: 'violent',
        quips: ['碾碎你！', '巨人之力！', '数字的重量压垮你！'],
        defendQuips: ['巨石防御！', '不可撼动！', '挡！'],
        enrageQuips: ['暴怒！！', '毁灭一切！', '巨人之怒！'],
        trait: '力大无穷的数字巨人，HP极高',
        traitEn: 'A titan of immense power made of numbers, extremely high HP',
        story: '数字巨人是由0到9所有数字堆叠而成的庞然大物。它的每一步都会让大地震动，每一拳都带着数学的重量。只有持续正确的答案才能削弱它巨大的身躯。',
        storyEn: 'A colossal being formed from all digits 0-9, each step shakes the earth.',
        isChapterMonster: true,
        chapter: 'xjj_ch3'
    },
    {
        id: 'xjj_ch3_phoenix',
        name: '不死鸟',
        nameEn: 'Math Phoenix',
        emoji: '🦅',
        hp: 6,
        type: 'fire',
        attack: '🔥',
        attackName: '涅槃烈焰',
        behaviors: ['heal', 'enrage'],
        personality: 'violent',
        quips: ['浴火重生！', '火焰永不熄灭！', '涅槃！'],
        enrageQuips: ['怒焰焚天！', '灰烬中重生！', '燃烧吧！'],
        healQuips: ['生命之火！', '回复！', '重生！'],
        trait: '被击倒会回血的火鸟，需要连续输出',
        traitEn: 'A phoenix that heals when knocked down, requiring sustained damage',
        story: '不死鸟是魔帝军团中最难缠的敌人——它能从灰烬中重生并恢复生命。只有连续答对题目，不给它喘息的机会，才能彻底击败它。',
        storyEn: 'The most persistent enemy, reborn from ashes. Only sustained correct answers can defeat it.',
        isChapterMonster: true,
        chapter: 'xjj_ch3'
    },
    {
        id: 'xjj_ch3_hydra',
        name: '九头蛇',
        nameEn: 'Nine-Headed Hydra',
        emoji: '🐲',
        hp: 7,
        type: 'dragon',
        attack: '🐉',
        attackName: '九头齐攻',
        behaviors: ['summon', 'enrage'],
        personality: 'sinister',
        quips: ['九个头，九道题！', '砍掉一个长两个！', '九九之力！'],
        summonQuips: ['再生一头！', '新的头颅！', '无穷无尽！'],
        enrageQuips: ['九头齐怒！', '全部一起上！', '毁灭！'],
        trait: '砍掉一头长出两头的九头蛇，会召唤增援',
        traitEn: 'Cut one head and two grow back, summons reinforcements',
        story: '九头蛇是魔帝最得意的造物——九个头分别代表1到9的乘法。每当你击败一个头，就会长出更多。只有一次性全部答对，才能阻止它的再生。',
        storyEn: 'The Emperor\'s proudest creation, nine heads representing multiplication by 1-9.',
        isChapterMonster: true,
        chapter: 'xjj_ch3'
    },
    {
        id: 'xjj_ch3_specter',
        name: '幻数幽灵',
        nameEn: 'Number Specter',
        emoji: '👻',
        hp: 5,
        type: 'ghost',
        attack: '👻',
        attackName: '数字扭曲',
        behaviors: ['dodge', 'curse'],
        personality: 'sinister',
        quips: ['数字在扭曲…', '幽灵飘过…', '看清楚了吗？还是幻觉？'],
        dodgeQuips: ['穿墙而过！', '幽灵无形！', '消失…'],
        curseQuips: ['数字幻象！', '混淆！', '什么都看不清了…'],
        trait: '让数字扭曲的幽灵，难以命中且会混淆',
        traitEn: 'A ghost that distorts numbers, hard to hit and causes confusion',
        story: '幻数幽灵是死去的数学家的怨念化成的幽灵。它能让你眼前的数字扭曲变形，6变成9，3变成8。在它面前保持清醒的头脑，才能看透幻象。',
        storyEn: 'A ghost born from a mathematician\'s grudge, distorting numbers before your eyes.',
        isChapterMonster: true,
        chapter: 'xjj_ch3'
    },
    {
        id: 'xjj_ch3_knight',
        name: '黑骑士',
        nameEn: 'Dark Knight',
        emoji: '🏇',
        hp: 7,
        type: 'steel',
        attack: '⚔️',
        attackName: '骑士冲锋',
        behaviors: ['defend', 'counter'],
        personality: 'defensive',
        quips: ['魔帝亲卫队！参上！', '骑士之誓！', '为魔帝效忠！'],
        defendQuips: ['骑士护盾！', '铁壁防御！', '不动如山！'],
        counterQuips: ['骑士反击！', '冲锋！', '接受制裁！'],
        trait: '魔帝亲卫队骑士，攻守兼备',
        traitEn: 'A knight of the Emperor\'s personal guard, balanced in offense and defense',
        story: '黑骑士是九九魔帝亲卫队的精锐，身穿由数学公式锻造的铠甲。它的信条是"防守即是最好的攻击"，任何计算失误都会遭到它坚定的反击。',
        storyEn: 'An elite of the Emperor\'s guard wearing armor forged from mathematical formulas.',
        isChapterMonster: true,
        chapter: 'xjj_ch3'
    },
    {
        id: 'xjj_ch3_chimera',
        name: '合成兽',
        nameEn: 'Math Chimera',
        emoji: '🦁',
        hp: 7,
        type: 'dragon',
        attack: '🦁',
        attackName: '三头连击',
        behaviors: ['enrage', 'dodge'],
        personality: 'violent',
        quips: ['三种野兽的力量！', '狮头、蛇尾、鹰翼！', '合成之力！'],
        enrageQuips: ['三头齐怒！', '暴走！', '不可阻挡！'],
        dodgeQuips: ['鹰翼闪避！', '三头切换！', '哪个头？'],
        trait: '多种野兽合成的怪物，暴怒且灵活',
        traitEn: 'A chimera combining multiple beasts, both enraged and agile',
        story: '合成兽是魔帝用三种数学概念——加法的狮头、乘法的蛇尾、除法的鹰翼——拼合而成的怪物。三种力量的结合使它既暴烈又灵活。',
        storyEn: 'Created by the Emperor from three math concepts: addition (lion), multiplication (snake), division (eagle).',
        isChapterMonster: true,
        chapter: 'xjj_ch3'
    },
    {
        id: 'xjj_ch3_warlock',
        name: '混沌法师',
        nameEn: 'Chaos Warlock',
        emoji: '🔮',
        hp: 6,
        type: 'psychic',
        attack: '🌀',
        attackName: '混沌召唤',
        behaviors: ['curse', 'summon'],
        personality: 'sinister',
        quips: ['混沌降临！', '秩序崩坏！', '在混沌中迷失吧！'],
        curseQuips: ['混沌诅咒！', '数字混乱！', '迷失方向！'],
        summonQuips: ['混沌召唤！', '从虚空中来！', '混沌仆从！'],
        trait: '召唤混沌干扰计算的法师，诅咒与召唤兼备',
        traitEn: 'A warlock that summons chaos to disrupt calculations',
        story: '混沌法师掌握着"混沌数学"——一种能让所有计算规则崩坏的禁忌魔法。在它面前，加法可能变减法，乘法可能变除法。只有坚定的数学基础才能抵抗混沌。',
        storyEn: 'Master of "Chaos Mathematics", a forbidden art that corrupts calculation rules.',
        isChapterMonster: true,
        chapter: 'xjj_ch3'
    },
    {
        id: 'xjj_ch3_general',
        name: '魔帝先锋',
        nameEn: 'Emperor\'s Vanguard',
        emoji: '⚔️',
        hp: 8,
        type: 'fighting',
        attack: '💥',
        attackName: '先锋连击',
        behaviors: ['enrage', 'counter', 'defend'],
        personality: 'violent',
        quips: ['魔帝军团先锋！', '挡我者死！', '为魔帝开路！'],
        enrageQuips: ['先锋暴走！', '全力突进！', '势不可挡！'],
        counterQuips: ['先锋反击！', '破！', '接招！'],
        defendQuips: ['先锋之盾！', '防御阵型！', '挡住！'],
        trait: '魔帝军团的先锋大将，三种战术切换',
        traitEn: 'The Emperor\'s vanguard general, switches between three combat tactics',
        story: '魔帝先锋是九九魔帝座下最强的将领，精通攻、防、反三种战术。它是挑战魔帝前的最后考验——能击败它的人，才有资格面对九九魔帝本尊。',
        storyEn: 'The Emperor\'s strongest general, master of attack, defense, and counter tactics.',
        isChapterMonster: true,
        chapter: 'xjj_ch3'
    },
    {
        id: 'xjj_ch3_cerberus',
        name: '守门三头犬',
        nameEn: 'Gate Cerberus',
        emoji: '🐕',
        hp: 7,
        type: 'dark',
        attack: '🐾',
        attackName: '三头撕咬',
        behaviors: ['counter', 'enrage'],
        personality: 'violent',
        quips: ['汪汪汪！三个头都要答！', '王座殿前的守卫！', '通不过！'],
        counterQuips: ['反咬！', '三头反击！', '不自量力！'],
        enrageQuips: ['三头齐吠！', '狂暴！', '撕碎一切！'],
        trait: '王座殿前最后的守卫，反击凶猛',
        traitEn: 'The final guardian before the throne room, fierce counterattacker',
        story: '守门三头犬守护着通往魔帝王座的最后一道门。它的三个头分别能闻到"犹豫"、"错误"和"恐惧"的气味。只有带着全对的自信才能从它面前通过。',
        storyEn: 'Guards the last door to the throne, its three heads smell hesitation, mistakes, and fear.',
        isChapterMonster: true,
        chapter: 'xjj_ch3'
    }
];

// ===== Chapter Exclusive Items =====
var chapterItems = {
    xiaojiujiu: [
        // Original star-reward items
        {
            id: 'xjj_ch1_stone_talisman',
            name: '石之护符',
            emoji: '🪨',
            type: 'buff',
            effect: { shield: 1 },
            desc: '口诀初试纪念：抵挡1次攻击',
            rarity: 'rare',
            chapter: 'xjj_ch1'
        },
        {
            id: 'xjj_ch2_speed_amulet',
            name: '疾风符',
            emoji: '💨',
            type: 'buff',
            effect: { timeBonus: 1500 },
            desc: '速算战场纪念：答题时间+1.5秒',
            rarity: 'epic',
            chapter: 'xjj_ch2'
        },
        {
            id: 'xjj_ch3_emperor_crown',
            name: '魔帝之冠',
            emoji: '👑',
            type: 'buff',
            effect: { allStatsUp: 2, comboBonus: 5 },
            desc: '魔王挑战纪念：全属性+2，连击+5',
            rarity: 'legendary',
            chapter: 'xjj_ch3'
        },
        // v23.1: New chapter drop items (2 per chapter)
        {
            id: 'xjj_ch1_abacus_bead',
            name: '算盘珠串',
            emoji: '📿',
            type: 'buff',
            effect: { comboBonus: 2 },
            desc: '口诀精灵的馈赠：连击+2',
            rarity: 'rare',
            chapter: 'xjj_ch1',
            isChapterDrop: true
        },
        {
            id: 'xjj_ch1_chalk_dust',
            name: '粉笔灰',
            emoji: '🤍',
            type: 'buff',
            effect: { timeBonus: 1000 },
            desc: '口诀精灵的馈赠：答题时间+1秒',
            rarity: 'rare',
            chapter: 'xjj_ch1',
            isChapterDrop: true
        },
        {
            id: 'xjj_ch2_swift_scroll',
            name: '疾风卷轴',
            emoji: '📜',
            type: 'buff',
            effect: { doubleHit: true },
            desc: '速算武士的秘传：双重打击',
            rarity: 'epic',
            chapter: 'xjj_ch2',
            isChapterDrop: true
        },
        {
            id: 'xjj_ch2_thunder_drum',
            name: '雷鼓',
            emoji: '🥁',
            type: 'buff',
            effect: { damage: 3 },
            desc: '速算武士的战鼓：额外伤害+3',
            rarity: 'epic',
            chapter: 'xjj_ch2',
            isChapterDrop: true
        },
        {
            id: 'xjj_ch3_dragon_scale',
            name: '龙鳞',
            emoji: '🛡️',
            type: 'buff',
            effect: { shield: 2 },
            desc: '魔帝军团的战利品：护盾+2',
            rarity: 'legendary',
            chapter: 'xjj_ch3',
            isChapterDrop: true
        },
        {
            id: 'xjj_ch3_emperor_seal',
            name: '帝王印',
            emoji: '🔱',
            type: 'buff',
            effect: { allStatsUp: 3, critChance: 0.25 },
            desc: '魔帝的印章：全属性+3，暴击率25%',
            rarity: 'legendary',
            chapter: 'xjj_ch3',
            isChapterDrop: true
        }
    ]
};

// ===== Chapter Exclusive Weapons =====
var chapterWeapons = {
    xiaojiujiu: [
        // Original 3-star reward weapons
        { emoji: '📖', name: '口诀之书', weight: 10, sound: 'holy', color: '#4a90d9', chapter: 'xjj_ch1' },
        { emoji: '⚔️', name: '将军之剑', weight: 10, sound: 'thunder', color: '#c0392b', chapter: 'xjj_ch2' },
        { emoji: '👑', name: '帝王权杖', weight: 12, sound: 'rainbow', color: '#f1c40f', chapter: 'xjj_ch3' }
    ]
};

// v23.1: New chapter flying weapons (added to weapon pool during chapter battles)
var chapterFlyingWeapons = {
    xiaojiujiu: [
        { emoji: '🪃', name: '口诀回旋镖', weight: 8, sound: 'wind', color: '#6c5ce7', chapter: 'xjj_ch1' },
        { emoji: '🗡️', name: '速算太刀', weight: 8, sound: 'thunder', color: '#e17055', chapter: 'xjj_ch2' },
        { emoji: '🔱', name: '魔帝三叉戟', weight: 10, sound: 'rainbow', color: '#fdcb6e', chapter: 'xjj_ch3' }
    ]
};

// ===== Main Chapter Configuration =====
var ChapterConfig = {
    xiaojiujiu: {
        theme: '妖怪',
        chapters: [
            {
                id: 'xjj_ch1',
                name: '口诀初试',
                subtitle: '掌握基础口诀',
                icon: '📖',
                stageCount: 9,  // 8 chapter monsters + 1 boss
                chapterMonsters: chapterMonsters_ch1,  // v23.1: use chapter-exclusive monsters
                questionPools: ['warmup', 'easy'],
                questionRatio: { warmup: 0.3, easy: 0.7 },
                playerHP: 5,
                baseDifficulty: 'easy',
                warmupFirst: 2,  // First 2 questions are warmup
                boss: chapterBossMonsters.xiaojiujiu[0],
                unlockCondition: null,  // Always unlocked
                rewards: {
                    firstClear: { score: 50, crystals: 5 },
                    star1: { item: 'xjj_ch1_stone_talisman' },
                    star2: { crystals: 10, guaranteedCardRarity: 'R' },
                    star3: { weapon: 'xjj_ch1_book', crystals: 20 }
                }
            },
            {
                id: 'xjj_ch2',
                name: '速算战场',
                subtitle: '考验速度与准确',
                icon: '⚔️',
                stageCount: 13,  // 12 chapter monsters + 1 boss
                chapterMonsters: chapterMonsters_ch2,  // v23.1: use chapter-exclusive monsters
                questionPools: ['easy', 'normal'],
                questionRatio: { easy: 0.3, normal: 0.7 },
                playerHP: 5,
                baseDifficulty: 'normal',
                forceInputAfterStage: 5,  // From stage 5, 40% chance of forceInput
                forceInputChance: 0.4,
                boss: chapterBossMonsters.xiaojiujiu[1],
                unlockCondition: { chapter: 'xjj_ch1', consecutivePerfects: 2 },  // v23.1: need 2 consecutive perfects
                rewards: {
                    firstClear: { score: 100, crystals: 10 },
                    star1: { item: 'xjj_ch2_speed_amulet' },
                    star2: { crystals: 20, guaranteedCardRarity: 'SR' },
                    star3: { weapon: 'xjj_ch2_sword', crystals: 30 }
                }
            },
            {
                id: 'xjj_ch3',
                name: '魔王挑战',
                subtitle: '终极速算大考验',
                icon: '👑',
                stageCount: 14,  // 13 chapter monsters + 1 boss
                chapterMonsters: chapterMonsters_ch3,  // v23.1: use chapter-exclusive monsters
                questionPools: ['easy', 'normal', 'hard'],
                questionRatio: { easy: 0.1, normal: 0.25, hard: 0.65 },
                playerHP: 5,
                baseDifficulty: 'hard',
                forceInputEvery: 3,  // Every 3 questions, 1 is forceInput
                bossOnlyHard: true,  // Boss fight only uses hard questions
                boss: chapterBossMonsters.xiaojiujiu[2],
                unlockCondition: { chapter: 'xjj_ch2', consecutivePerfects: 3 },  // v23.1: need 3 consecutive perfects
                rewards: {
                    firstClear: { score: 200, crystals: 20 },
                    star1: { item: 'xjj_ch3_emperor_crown' },
                    star2: { crystals: 40, guaranteedCardRarity: 'SSR' },
                    star3: { weapon: 'xjj_ch3_scepter', crystals: 50, title: '九九征服者' }
                }
            }
        ]
    }
    // Other modules (fraction, decimal, unit, multiply, times) will be added in future versions
};

// ===== Star Rating Configuration =====
var ChapterStarConfig = {
    // Star 1 (bronze): pass with >= 50% accuracy
    star1: { accuracy: 0.50 },
    // Star 2 (silver): >= 80% accuracy
    star2: { accuracy: 0.80 },
    // Star 3 (gold): >= 95% accuracy AND no death (HP never reached 0)
    star3: { accuracy: 0.95, noDeath: true }
};
